<div class="imageresizer">
	<div class="block">
	<div class="draganddrop"><p>Drag and Drop the Files</p></div>
	</div>
	<input type="file" id="file-input" multiple />
	<input type="number" id="widthVal" placeholder="width" />
	<input type="number" id="heightVal" placeholder="height" />
	<p id="actions">
		<button type="button" id="resize">resize</button>
		<button type="button" id="clear">clear</button>
		<!-- <button type="button" id="edit">edit</button> -->
		<button id="download"><span>download</span></button>
	</p>
	<img class="logo" src="media/images/lama.png">
</div>
<div id="imagecollection">
	<div id="list"></div>
</div>
<div id="result" class="result">
</div>
<form class="outputfiles">
	<div id="storage"></div>
</form>
<div id="to-top"><span>Top</span></div>
