<div class="imageresizer">
	<div class="block">
	<div class="draganddrop"><p>Drag and Drop the Files</p></div>
	</div>
	<input type="file" id="file-input" multiple />
	<input type="number" id="widthVal" placeholder="width" />
	<input type="number" id="heightVal" placeholder="height" />
	<p id="actions">
		<button type="button" id="resize">resize</button>
		<button type="button" id="edit">edit</button>
		<button id="download"><span>download</span></button>
	</p>
</div>
<div id="result" class="result">
</div>
<form class="outputfiles">
 	<div id="list"></div>
	<div id="storage"></div>
</form>

